import os
os.system('git pull')
import error32_enc
